import React, { useState } from 'react';
import { Zap, Smartphone, ArrowRight, CheckCircle, Loader, Terminal, Apple, Upload, FileCode } from 'lucide-react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';

export default function OneClick() {
    const [step, setStep] = useState(1);
    const [file, setFile] = useState(null);
    const [platform, setPlatform] = useState('ios');
    const [processing, setProcessing] = useState(false);
    const [logs, setLogs] = useState([]);

    // RUNPOD CONFIGURATION (Replace these with your real values!)
    const RUNPOD_ID = "YOUR_RUNPOD_ENDPOINT_ID"; 
    const RUNPOD_API_KEY = "YOUR_RUNPOD_API_KEY"; 

    const addLog = (msg) => setLogs(prev => [...prev, msg]);

    const handleFileChange = (e) => {
        if (e.target.files && e.target.files[0]) {
            setFile(e.target.files[0]);
            addLog(`> Selected file: ${e.target.files[0].name}`);
        }
    };

    const callRunPod = async () => {
        if (!file) return;
        setProcessing(true);
        setStep(2);
        addLog("> Uploading model to GPU Engine...");

        try {
            // 1. In a real app, you upload the file to S3/Supabase first.
            // For this demo, we send the filename to the GPU to simulate the trigger.
            addLog("> Sending job to RunPod Serverless...");

            const response = await fetch(`https://api.runpod.ai/v2/${RUNPOD_ID}/runsync`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "Authorization": `Bearer ${RUNPOD_API_KEY}`
                },
                body: JSON.stringify({
                    input: {
                        file_name: file.name,
                        platform: platform,
                        operation: "compress"
                    }
                })
            });

            const data = await response.json();
            
            if (data.status === "COMPLETED") {
                addLog("> GPU Compression Successful!");
                addLog(`> Output: ${data.output.message}`);
                addLog(`> New Size: ${data.output.new_size}`);
                await generateProject();
            } else {
                addLog("> GPU Job Failed or Timed Out.");
                console.error(data);
                setProcessing(false);
            }

        } catch (err) {
            addLog(`> Error: ${err.message}`);
            setProcessing(false);
        }
    };

    const generateProject = async () => {
        addLog(`> Generating ${platform.toUpperCase()} Project structure...`);
        const zip = new JSZip();
        
        // Create Real Project Folder
        const root = zip.folder(`AIGO_${platform.toUpperCase()}_Export`);
        root.file("README.md", `# AIGO Export for ${platform}\n\nGenerated by AIGO Engine.`);
        
        if (platform === 'ios') {
            root.file("ModelView.swift", "// Swift CoreML bindings...");
            root.file("AIGO.mlmodel", "PLACEHOLDER_FOR_REAL_MODEL"); 
        } else {
            root.file("MainActivity.kt", "// Kotlin TFLite bindings...");
            root.file("model.tflite", "PLACEHOLDER_FOR_REAL_MODEL");
        }

        const content = await zip.generateAsync({ type: "blob" });
        saveAs(content, `AIGO_${platform}_Export.zip`);
        
        addLog("> DOWNLOAD STARTED.");
        setProcessing(false);
        setStep(3);
    };

    return (
        <div className="fade-in font-['Outfit'] text-white">
            <div className="flex items-center gap-4 mb-8">
                <div className="w-12 h-12 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-xl flex items-center justify-center shadow-lg">
                    <Zap size={24} className="text-white" />
                </div>
                <div>
                    <h1 className="text-3xl font-black italic">GPU ENGINE DEPLOY</h1>
                    <p className="text-slate-400">Powered by RunPod Serverless (A100/T4 GPUs)</p>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 max-w-5xl">
                {/* LEFT: INPUT */}
                <div className="bg-[#0f172a] border border-slate-800 rounded-2xl p-8">
                    <h3 className="font-bold text-lg mb-6">1. Select Model & Target</h3>
                    <div className="border-2 border-dashed border-slate-700 rounded-xl p-8 text-center hover:border-indigo-500 transition relative cursor-pointer">
                        <input type="file" onChange={handleFileChange} className="absolute inset-0 opacity-0 cursor-pointer" />
                        <Upload className="mx-auto text-slate-500 mb-2" />
                        <p className="text-sm font-bold text-white">{file ? file.name : "Upload .pt / .onnx"}</p>
                    </div>

                    <div className="grid grid-cols-2 gap-3 mt-6">
                        <button onClick={() => setPlatform('ios')} className={`p-3 rounded-lg border text-sm font-bold flex items-center justify-center gap-2 ${platform === 'ios' ? 'bg-white text-black' : 'bg-[#020617] text-slate-400'}`}><Apple size={16}/> iOS</button>
                        <button onClick={() => setPlatform('android')} className={`p-3 rounded-lg border text-sm font-bold flex items-center justify-center gap-2 ${platform === 'android' ? 'bg-[#3ddc84] text-black' : 'bg-[#020617] text-slate-400'}`}><Smartphone size={16}/> Android</button>
                    </div>

                    <button onClick={callRunPod} disabled={!file || processing} className="w-full mt-6 py-4 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-xl transition flex items-center justify-center gap-2 disabled:opacity-50">
                        {processing ? <Loader className="animate-spin"/> : <Zap/>} {processing ? 'Processing on GPU...' : 'Deploy to Edge'}
                    </button>
                </div>

                {/* RIGHT: REAL-TIME LOGS */}
                <div className="bg-[#020617] border border-slate-800 rounded-2xl p-6 font-mono text-xs text-slate-400 overflow-y-auto h-[400px] shadow-inner">
                    <div className="mb-2 text-indigo-400 font-bold border-b border-indigo-500/30 pb-2">AIGO ENGINE LOGS</div>
                    {logs.length === 0 && <span className="opacity-50">Waiting for job...</span>}
                    {logs.map((log, i) => (
                        <div key={i} className="mb-1">{log}</div>
                    ))}
                    {processing && <div className="animate-pulse mt-2 text-indigo-400">_</div>}
                </div>
            </div>
        </div>
    );
}