import React, { useState } from 'react';
import { Zap, Smartphone, ArrowRight, CheckCircle, Loader, Terminal, Apple, Upload, FileCode } from 'lucide-react';
import DashboardLayout from '../components/DashboardLayout';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import toast from 'react-hot-toast';

export default function OneClick() {
  const [step, setStep] = useState(1);
  const [file, setFile] = useState(null);
  const [platform, setPlatform] = useState('ios');
  const [processing, setProcessing] = useState(false);
  const [logs, setLogs] = useState([]);

  // RUNPOD CONFIGURATION (Replace these with your real values!)
  const RUNPOD_ID = "YOUR_RUNPOD_ENDPOINT_ID"; 
  const RUNPOD_API_KEY = "YOUR_RUNPOD_API_KEY"; 

  const addLog = (msg) => setLogs(prev => [...prev, msg]);

  const handleFileChange = (e) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
      addLog(`> Selected file: ${e.target.files[0].name}`);
      toast.success(`Selected: ${e.target.files[0].name}`);
    }
  };

  const callRunPod = async () => {
    if (!file) {
      toast.error('Please select a model file first');
      return;
    }
    
    setProcessing(true);
    setStep(2);
    addLog("> Uploading model to GPU Engine...");

    try {
      // 1. In a real app, you upload the file to S3/Supabase first.
      // For this demo, we send the filename to the GPU to simulate the trigger.
      addLog("> Sending job to RunPod Serverless...");

      const response = await fetch(`https://api.runpod.ai/v2/${RUNPOD_ID}/runsync`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${RUNPOD_API_KEY}`
        },
        body: JSON.stringify({
          input: {
            file_name: file.name,
            platform: platform,
            operation: "compress"
          }
        })
      });

      const data = await response.json();
      
      if (data.status === "COMPLETED") {
        addLog("> GPU Compression Successful!");
        addLog(`> Output: ${data.output.message}`);
        addLog(`> New Size: ${data.output.new_size}`);
        await generateProject();
      } else {
        addLog("> GPU Job Failed or Timed Out.");
        console.error(data);
        toast.error('GPU processing failed');
        setProcessing(false);
      }

    } catch (err) {
      addLog(`> Error: ${err.message}`);
      toast.error(`Error: ${err.message}`);
      setProcessing(false);
    }
  };

  const generateProject = async () => {
    addLog(`> Generating ${platform.toUpperCase()} Project structure...`);
    const zip = new JSZip();
    
    // Create Real Project Folder
    const root = zip.folder(`AIGO_${platform.toUpperCase()}_Export`);
    root.file("README.md", `# AIGO Export for ${platform}\n\nGenerated by AIGO Engine.\n\n## Quick Start\n\n1. Open the project in ${platform === 'ios' ? 'Xcode' : 'Android Studio'}\n2. Build and run on your device\n3. The model is already integrated!`);
    
    if (platform === 'ios') {
      root.file("ModelView.swift", `import SwiftUI
import CoreML

struct ModelView: View {
    var body: some View {
        Text("AIGO Model Ready")
            .font(.title)
            .padding()
    }
}

// TODO: Load your CoreML model here
`);
      root.file("AIGO.mlmodel", "PLACEHOLDER_FOR_REAL_MODEL"); 
      root.file("Info.plist", `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>AIGO App</string>
</dict>
</plist>`);
    } else {
      root.file("MainActivity.kt", `package com.aigo.app

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        // TODO: Load TFLite model
    }
}
`);
      root.file("model.tflite", "PLACEHOLDER_FOR_REAL_MODEL");
      root.file("build.gradle", `dependencies {
    implementation 'org.tensorflow:tensorflow-lite:2.13.0'
}`);
    }

    const content = await zip.generateAsync({ type: "blob" });
    saveAs(content, `AIGO_${platform}_Export.zip`);
    
    addLog("> DOWNLOAD STARTED.");
    toast.success('Project exported successfully!');
    setProcessing(false);
    setStep(3);
  };

  return (
    <DashboardLayout>
      <div className="min-h-screen bg-[#0f1420] p-6 lg:p-8">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <div className="flex items-center gap-4 mb-8">
            <div className="w-14 h-14 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-2xl flex items-center justify-center shadow-lg shadow-indigo-500/30">
              <Zap size={28} className="text-white" />
            </div>
            <div>
              <h1 className="text-4xl font-black text-white italic">GPU ENGINE DEPLOY</h1>
              <p className="text-slate-400 mt-1">Powered by RunPod Serverless (A100/T4 GPUs)</p>
            </div>
          </div>

          {/* Step Indicator */}
          <div className="mb-8 flex items-center justify-center gap-4">
            {[1, 2, 3].map((s) => (
              <div key={s} className="flex items-center">
                <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold transition ${
                  step >= s 
                    ? 'bg-gradient-to-br from-indigo-500 to-purple-600 text-white' 
                    : 'bg-slate-800 text-slate-500'
                }`}>
                  {step > s ? <CheckCircle size={20} /> : s}
                </div>
                {s < 3 && (
                  <div className={`w-16 h-1 mx-2 transition ${
                    step > s ? 'bg-gradient-to-r from-indigo-500 to-purple-600' : 'bg-slate-800'
                  }`} />
                )}
              </div>
            ))}
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* LEFT: INPUT */}
            <div className="bg-[#1a1f2e] border border-slate-800 rounded-2xl p-8">
              <h3 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
                <Upload size={20} className="text-indigo-400" />
                1. Select Model & Target Platform
              </h3>
              
              <div className="border-2 border-dashed border-slate-700 rounded-2xl p-10 text-center hover:border-indigo-500 transition relative cursor-pointer bg-slate-900/30">
                <input 
                  type="file" 
                  onChange={handleFileChange} 
                  className="absolute inset-0 opacity-0 cursor-pointer" 
                  accept=".pt,.pth,.onnx,.h5,.tflite"
                />
                <Upload className="mx-auto text-slate-500 mb-3" size={40} />
                {file ? (
                  <>
                    <p className="text-sm font-bold text-white mb-1">{file.name}</p>
                    <p className="text-xs text-slate-400">{(file.size / (1024 * 1024)).toFixed(2)} MB</p>
                  </>
                ) : (
                  <>
                    <p className="text-sm font-bold text-white mb-1">Upload Model File</p>
                    <p className="text-xs text-slate-400">Supports .pt, .onnx, .h5, .tflite</p>
                  </>
                )}
              </div>

              <div className="mt-6">
                <label className="block text-sm font-semibold text-slate-400 mb-3">Target Platform</label>
                <div className="grid grid-cols-2 gap-4">
                  <button 
                    onClick={() => setPlatform('ios')} 
                    className={`p-4 rounded-xl border-2 transition text-sm font-bold flex items-center justify-center gap-2 ${
                      platform === 'ios' 
                        ? 'bg-white text-black border-white' 
                        : 'bg-[#0f1420] text-slate-400 border-slate-700 hover:border-slate-600'
                    }`}
                  >
                    <Apple size={20}/> iOS (CoreML)
                  </button>
                  <button 
                    onClick={() => setPlatform('android')} 
                    className={`p-4 rounded-xl border-2 transition text-sm font-bold flex items-center justify-center gap-2 ${
                      platform === 'android' 
                        ? 'bg-[#3ddc84] text-black border-[#3ddc84]' 
                        : 'bg-[#0f1420] text-slate-400 border-slate-700 hover:border-slate-600'
                    }`}
                  >
                    <Smartphone size={20}/> Android (TFLite)
                  </button>
                </div>
              </div>

              <button 
                onClick={callRunPod} 
                disabled={!file || processing} 
                className="w-full mt-8 py-4 bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-400 hover:to-purple-500 text-white font-bold rounded-xl transition flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-indigo-500/30"
              >
                {processing ? (
                  <>
                    <Loader className="animate-spin" size={20}/> 
                    Processing on GPU...
                  </>
                ) : (
                  <>
                    <Zap size={20}/> 
                    Deploy to Edge Device
                  </>
                )}
              </button>
            </div>

            {/* RIGHT: REAL-TIME LOGS */}
            <div className="bg-[#0f1420] border border-slate-800 rounded-2xl overflow-hidden">
              <div className="bg-slate-900 border-b border-slate-800 p-4 flex items-center gap-2">
                <Terminal size={18} className="text-indigo-400" />
                <span className="text-sm font-bold text-indigo-400">AIGO ENGINE LOGS</span>
              </div>
              <div className="p-6 font-mono text-xs text-slate-400 h-[500px] overflow-y-auto">
                {logs.length === 0 && (
                  <div className="flex items-center gap-2 opacity-50">
                    <div className="w-2 h-2 bg-slate-600 rounded-full animate-pulse"></div>
                    <span>Waiting for job...</span>
                  </div>
                )}
                {logs.map((log, i) => (
                  <div key={i} className="mb-2 flex items-start gap-2">
                   <span className="text-indigo-400 flex-shrink-0">▶</span>
                    <span>{log}</span>
                  </div>
                ))}
                {processing && (
                  <div className="flex items-center gap-2 mt-3 text-indigo-400">
                    <div className="w-2 h-2 bg-indigo-400 rounded-full animate-pulse"></div>
                    <span className="animate-pulse">Processing...</span>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Success Message */}
          {step === 3 && (
            <div className="mt-8 bg-gradient-to-r from-emerald-500/10 to-teal-500/10 border-2 border-emerald-500/30 rounded-2xl p-8 text-center">
              <div className="w-16 h-16 bg-emerald-500 rounded-full flex items-center justify-center mx-auto mb-4">
                <CheckCircle size={32} className="text-white" />
              </div>
              <h3 className="text-2xl font-bold text-white mb-2">Export Complete!</h3>
              <p className="text-slate-400 mb-6">Your {platform.toUpperCase()} project has been downloaded</p>
              <button
                onClick={() => {
                  setStep(1);
                  setFile(null);
                  setLogs([]);
                }}
                className="px-6 py-3 bg-slate-800 hover:bg-slate-700 text-white font-bold rounded-xl transition"
              >
                Export Another Model
              </button>
            </div>
          )}
        </div>
      </div>
    </DashboardLayout>
  );
}
